#!/bin/bash

sudo apt-get update

# Install a special package
$ sudo apt-get install -y python-software-properties python g++ make

# Add a new repository for apt-get to search
$ sudo add-apt-repository ppa:chris-lea/node.js

# Update apt-get’s knowledge of which packages are where
$ sudo apt-get update

# Now install nodejs and npm
sudo apt-get install -y nodejs
sudo apt-get install npm

#install git and heroku
sudo apt-get install -y git-core
wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh

#install screen
cd $HOME
wget raw.github.com/startup-class/dotfiles/master/.screenrc -O .screenrc

#install emacs
git clone https://github.com/startup-class/setup.git
./setup/setup.sh



